/**
 * Auto-generated by Payload — run `npm run generate:types` to regenerate.
 * This stub satisfies TypeScript until you run the dev server for the first time.
 */

export interface Config {
  collections: {
    users: User
    media: Media
    categories: Category
    authors: Author
    products: Product
    articles: Article
  }
  globals: {
    homepage: Homepage
  }
}

export interface User {
  id: string
  name?: string | null
  email: string
  createdAt: string
  updatedAt: string
}

export interface Media {
  id: string
  alt: string
  caption?: string | null
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  createdAt: string
  updatedAt: string
}

export interface Category {
  id: string
  name: string
  slug: string
  color?: ('terracotta' | 'sage' | 'blue' | 'sand') | null
  createdAt: string
  updatedAt: string
}

export interface Author {
  id: string
  name: string
  title?: string | null
  avatar?: (string | null) | Media
  bio?: string | null
  createdAt: string
  updatedAt: string
}

export interface Product {
  id: string
  name: string
  slug: string
  image?: (string | null) | Media
  price: number
  category?: (string | null) | Category
  description?: string | null
  material?: string | null
  dimensions?: string | null
  weight?: string | null
  colors?:
    | {
        label: string
        hex: string
        id?: string | null
      }[]
    | null
  inStock?: boolean | null
  createdAt: string
  updatedAt: string
}

export type ContentBlock =
  | RichTextBlock
  | ShoppableSceneBlock
  | SectionHeadingBlock
  | ProductCardBlock
  | StylingTipBlock
  | MaterialCalloutBlock
  | PullQuoteBlock
  | ImagePairBlock
  | BudgetBreakdownBlock

export interface RichTextBlock {
  blockType: 'richText'
  id?: string | null
  content?: any
}

export interface ShoppableSceneBlock {
  blockType: 'shoppableScene'
  id?: string | null
  image: string | Media
  caption?: string | null
  hotspots?:
    | {
        product: string | Product
        x: number
        y: number
        id?: string | null
      }[]
    | null
}

export interface SectionHeadingBlock {
  blockType: 'sectionHeading'
  id?: string | null
  number?: string | null
  heading: string
}

export interface ProductCardBlock {
  blockType: 'productCard'
  id?: string | null
  product: string | Product
  editorsNote?: string | null
  displayStyle?: ('full' | 'compact' | 'inline') | null
}

export interface StylingTipBlock {
  blockType: 'stylingTip'
  id?: string | null
  icon?: string | null
  label: string
  content: string
}

export interface MaterialCalloutBlock {
  blockType: 'materialCallout'
  id?: string | null
  icon?: string | null
  name: string
  description: string
}

export interface PullQuoteBlock {
  blockType: 'pullQuote'
  id?: string | null
  quote: string
  attribution?: string | null
}

export interface ImagePairBlock {
  blockType: 'imagePair'
  id?: string | null
  imageOne: string | Media
  imageTwo: string | Media
  caption?: string | null
}

export interface BudgetBreakdownBlock {
  blockType: 'budgetBreakdown'
  id?: string | null
  title?: string | null
  items?:
    | {
        product?: (string | null) | Product
        label?: string | null
        price?: number | null
        color?: string | null
        id?: string | null
      }[]
    | null
}

export interface Article {
  id: string
  title: string
  slug: string
  excerpt?: string | null
  heroImage?: (string | null) | Media
  category?: (string | null) | Category
  author?: (string | null) | Author
  readTime?: string | null
  featured?: boolean | null
  tags?: { tag?: string | null; id?: string | null }[] | null
  content?: ContentBlock[] | null
  createdAt: string
  updatedAt: string
}

export interface Homepage {
  id: string
  hero?: {
    heading?: string | null
    subheading?: string | null
    backgroundImage?: (string | null) | Media
    ctaText?: string | null
    ctaArticle?: (string | null) | Article
  }
  featuredArticles?: (string | Article)[] | null
  shoppableScene?: {
    image?: (string | null) | Media
    caption?: string | null
    hotspots?:
      | {
          product: string | Product
          x: number
          y: number
          id?: string | null
        }[]
      | null
  }
  trendingProducts?: (string | Product)[] | null
  createdAt: string
  updatedAt: string
}
